// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdNvS_txl2au4nkEoVv7-DITcMFpYB_XI',
    appId: '1:450790422852:web:dc006bdff60bd59a29ff11',
    messagingSenderId: '450790422852',
    projectId: 'aora-c1702',
    authDomain: 'aora-c1702.firebaseapp.com',
    storageBucket: 'aora-c1702.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtIWmkGBWOZVfI1r7evEkgFuswFzwl_rU',
    appId: '1:450790422852:android:13e0b46d7deed05a29ff11',
    messagingSenderId: '450790422852',
    projectId: 'aora-c1702',
    storageBucket: 'aora-c1702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrAVydECUxEeIC-Tfr7YFlj-ZCTtvQV4',
    appId: '1:450790422852:ios:eb0a5a08fcbf491e29ff11',
    messagingSenderId: '450790422852',
    projectId: 'aora-c1702',
    storageBucket: 'aora-c1702.firebasestorage.app',
    iosBundleId: 'com.aora.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrAVydECUxEeIC-Tfr7YFlj-ZCTtvQV4',
    appId: '1:450790422852:ios:eb0a5a08fcbf491e29ff11',
    messagingSenderId: '450790422852',
    projectId: 'aora-c1702',
    storageBucket: 'aora-c1702.firebasestorage.app',
    iosBundleId: 'com.aora.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdNvS_txl2au4nkEoVv7-DITcMFpYB_XI',
    appId: '1:450790422852:web:c272944149235cc429ff11',
    messagingSenderId: '450790422852',
    projectId: 'aora-c1702',
    authDomain: 'aora-c1702.firebaseapp.com',
    storageBucket: 'aora-c1702.firebasestorage.app',
  );
}
